# This file was generated by GoReleaser. DO NOT EDIT.
cask "flipt@2" do
  name "flipt@2"
  desc "A Git-first, CloudNative feature management solution"
  homepage "https://flipt.io"
  version "2.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flipt"

  on_macos do
    on_intel do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_darwin_x86_64.tar.gz"
      sha256 "6c2bd63836227582cba74d80f4cea5be06864a935894dab13a2c538d2c13a84e"
    end
    on_arm do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_darwin_arm64.tar.gz"
      sha256 "083b9293692da18eb421e14a7f41e9a57e6650fad843a9747a5ae9e035abb148"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_linux_x86_64.tar.gz"
      sha256 "e2668da73c9579bc2e9a0131f98ef8d08be9e84cc12474a401617d89a2459df8"
    end
    on_arm do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_linux_arm64.tar.gz"
      sha256 "935b42ca23b4c00c5094552a993e6e8d69a4a3315d21cb1207d3b99b0a3e0dcf"
    end
  end

  # No zap stanza required
end
