# This file was generated by GoReleaser. DO NOT EDIT.
cask "flipt@2" do
  name "flipt@2"
  desc "A Git-first, CloudNative feature management solution"
  homepage "https://flipt.io"
  version "2.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flipt"

  on_macos do
    on_intel do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_darwin_x86_64.tar.gz"
      sha256 "755369a89a3f4adf2982a19bb2655b7620e64ead95319ddceadf00cad30b33eb"
    end
    on_arm do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_darwin_arm64.tar.gz"
      sha256 "c7a935298f363170285553242bab30fa999695087350d64ba2390dd86da7458c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_linux_x86_64.tar.gz"
      sha256 "c701751a28e0ffa6a5a0135917673becc435fedcb9b563d29a6ee754de019e45"
    end
    on_arm do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_linux_arm64.tar.gz"
      sha256 "cbcb53cd9df9efb12774eb4eda7f2546f7f741e2ca3792d9cb42516bceabd056"
    end
  end

  # No zap stanza required
end
