# This file was generated by GoReleaser. DO NOT EDIT.
cask "flipt@2" do
  name "flipt@2"
  desc "A Git-first, CloudNative feature management solution"
  homepage "https://flipt.io"
  version "2.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flipt"

  on_macos do
    on_intel do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_darwin_x86_64.tar.gz"
      sha256 "991231447e6eeae88a66302bf78bafc2f43f8491da9e15a1a19b0bd39e7bf65b"
    end
    on_arm do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_darwin_arm64.tar.gz"
      sha256 "b4a25fed7d57dd762763da71b2e25eacd49777abba2945af603a3a4b9e2c0c32"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_linux_x86_64.tar.gz"
      sha256 "90995fbe36afe16b112f0836648ba0d52340deead1f6c7bfdfed23d4e76a7cd2"
    end
    on_arm do
      url "https://github.com/flipt-io/flipt/releases/download/v#{version}/flipt_linux_arm64.tar.gz"
      sha256 "cdf92aa7ce612f25aa30b1e17a4756abc0f75a8e4bd8137022bd16ba4287a20a"
    end
  end

  # No zap stanza required
end
