# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flipt < Formula
  desc "An open source, self-hosted feature flag solution"
  homepage "https://flipt.io"
  version "1.26.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/flipt-io/flipt/releases/download/v1.26.0/flipt_darwin_arm64.tar.gz"
      sha256 "fd659ccaa16e463262ffecf692a2e489b8f92f24e5071ab74f3d456d54d2bd53"

      def install
        bin.install "flipt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flipt-io/flipt/releases/download/v1.26.0/flipt_linux_arm64.tar.gz"
      sha256 "527cf19a261c4efd857b5fbea3c738cbcfe281baa1c33a81d0a41e433c42d4d2"

      def install
        bin.install "flipt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flipt-io/flipt/releases/download/v1.26.0/flipt_linux_x86_64.tar.gz"
      sha256 "65c75da2e9be58a23f5de48a3c9ff08604269e557660144b9e91610a2c5ccae3"

      def install
        bin.install "flipt"
      end
    end
  end

  def post_install
    (var/"log/flipt").mkpath
  end

  service do
    run [opt_bin/"flipt"]
    environment_variables PATH: std_service_path_env
    keep_alive true
    error_log_path "#{var}/log/flipt/server-stderr.log"
    log_path "#{var}/log/flipt/server-stdout.log"
  end
end
